### ISSUE TITLE
contentEditable is hard coded to true

### ISSUE THREAD

**Issue by thecaddy** [wangzuo/react-medium-editor#15]
Should adhere to medium editor options:

```
disableEditing

Default: false

Enables/disables adding the contenteditable behavior. Useful for using the toolbar with customized buttons/actions. You can also set specific element behavior by using setting a data-disable-editing attribute.
```

**Comment by hyperh** [comment]
Having same problem, can't set `disableEditing: true`. Setting it `true` has no effect.

**Comment by thecaddy** [comment]
I took what he did and updated it a bit if you wan to use it, here is a gist you can plop into your code and start using:

https://gist.github.com/thecaddy/61a63d92683ed1ebfb05

**Comment by shark0der** [comment]
I submitted a pull request some time ago https://github.com/wangzuo/react-medium-editor/pull/20 but the author of the repo doesn't seem to be very active. I guess this should be forked by someone who is willing to maintain the project.
