### ISSUE TITLE
Rendering on Firefox

### ISSUE THREAD

**Issue by riccardolorenzon** [wangzuo/react-medium-editor#4]
I'm using Firefox v 40.0.3 on Mac OSX 10.10.3. 

Copying and paste a large text inside the editors results in a thing like this:
![screen shot 2015-10-01 at 4 23 31 pm](https://cloud.githubusercontent.com/assets/1963568/10223331/cca3bac8-6858-11e5-84c2-47c4f036cd96.png)

**Comment by wangzuo** [comment]
I guess this is a css issue, you may refer to the css `word-break` property
