### ISSUE TITLE
Accessing Editor Events?

### ISSUE THREAD

**Issue by nicholasalanbrown** [wangzuo/react-medium-editor#5]
Hello:

How would I go about accessing editor events and helpers? I'm particularly interested in the "serialize()" method.

Thanks!

**Comment by wangzuo** [comment]
This is a medium editor instance `this.medium` within the component. Will that be helpful?

**Comment by vhpoet** [comment]
@wangzuo `this.medium` in `componentDidMount` is `undefined`.
