### ISSUE TITLE
Mozilla Firefox Error: Permission denied to access property "nodeType"

### ISSUE THREAD

**Issue by hakanozkaptan** [wangzuo/react-medium-editor#80]
Hi,

Mozilla firefox gives that error.
Error: Permission denied to access property "nodeType"

[https://gallery.mailchimp.com/7beaa7cd3a83d97913970c882/images/e06f8b32-6bf6-4e11-95c8-7a5e077e123d.png](https://gallery.mailchimp.com/7beaa7cd3a83d97913970c882/images/e06f8b32-6bf6-4e11-95c8-7a5e077e123d.png)

How can i fix.

**Comment by hakanozkaptan** [comment]
Okey my bad, I solved

**Comment by cfuller94** [comment]
@hakanozkaptan I'm also seeing this issue and couldn't find an easy solution to fix this in Firefox short of disabling the type="date" that was on the same page. Did you have a better solution?

**Comment by hakanozkaptan** [comment]
@cfuller94 I am so sorry, I don't remember how to fix it.

**Comment by cfuller94** [comment]
@hakanozkaptan https://xkcd.com/979/

**Comment by bryanpedini** [comment]
> I don't remember how to fix it.

why in this hell world you thought it was a good idea to write "my bad, fixed" and close your own issue, but not report how you did it?

I'm facing this same shit years later without having upgraded neither firefox nor my Gitea instance (which I control) and I duno wtf is causing me to not be able to login to my own goddamn server. I'm sorry, don't take it personal @hakanozkaptan, but I hate "fixed now" replies without any explanation...

**Comment by bravegrumpy** [comment]
> > I don't remember how to fix it.
> 
> why in this hell world you thought it was a good idea to write "my bad, fixed" and close your own issue, but not report how you did it?
> 
> I'm facing this same shit years later without having upgraded neither firefox nor my Gitea instance (which I control) and I duno wtf is causing me to not be able to login to my own goddamn server. I'm sorry, don't take it personal @hakanozkaptan, but I hate "fixed now" replies without any explanation...

I feel this. I''m now running into this error. I gotta love the "nvm fixed" response. 🤦‍♂️
